name: balance backroom approval check
on:
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]
jobs:
  check-pr:
    name: Backroom approval (PR update)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check labels
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        continue-on-error: true
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            invalid-labels: 'character change'
            pull-request-number: '${{ github.event.pull_request.number }}${{ github.event.issue.number }}'
            disable-reviews: true

      - name: this is a character change
        if: failure()
        id: is_character
        run: echo "is_character=yes" >> $GITHUB_OUTPUT

      - run: echo '${{ github.event.pull_request.number }}${{ github.event.issue.number }}'

      - name: Check for comment approval
        uses: peter-evans/find-comment@v2
        id: approval
        if: always()
        with:
          issue-number: '${{ github.event.pull_request.number }}${{ github.event.issue.number }}'
          comment-author: hdr-balance-backroom
          body-includes: APPROVED

      - run: |
          echo "is character: ${{ steps.is_character.outputs.is_character }}, comment id: ${{ steps.approval.outputs.comment-id }}"

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.is_character.outputs.is_character == 'yes' && steps.approval.outputs.comment-id == 0
        with:
          header: explain
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            This Pull Request is labeled as a character change, but has not yet been approved by balance backroom.

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.is_character.outputs.is_character == 'yes' && steps.approval.outputs.comment-id != 0
        with:
          header: explain
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            This Pull Request has been approved by balance backroom.

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.is_character.outputs.is_character != 'yes'
        with:
          header: explain
          hide: true
          hide_classify: 'OUTDATED'
          
      - name: determine if approved
        if: steps.approval.outputs.comment-id == 0 && steps.is_character.outputs.is_character == 'yes'
        run: exit 1
